### ISSUE TITLE
作者您好,我刚刚尝试了您最新版本的 gpt 插件,想问问这个工作流是怎么样的?

### ISSUE THREAD

**Issue by z2332677** [MuiseDestiny/zotero-gpt-helper#2]

**Comment by z2332677** [comment]
这个插件是自动识别我当前打开了什么文章吗?

**Comment by z2332677** [comment]
而且如果我换了一篇文章 他会检测到新的文章 然后根据新的文章的内容回答问题吗?

**Comment by MuiseDestiny** [comment]
你输入问题，点askPDF，你当前读哪一篇，他就根据那一篇回答。每个pdf只需要建立一次gpt index。

**Comment by MuiseDestiny** [comment]
目前正在评估它与chatPDF的区别，他与chatPDF原理相同。

借鉴了目前已有的优秀的文件问答项目。

![image](https://user-images.githubusercontent.com/51939531/230631651-bb851a01-915d-4c7d-bd21-e1fa5fb6c9b6.png)

**Comment by MuiseDestiny** [comment]
请问你打通AskPDF了吗，因为我不确定文档写的是否详细，用户参照能否配置成功

**Comment by z2332677** [comment]
<img width="516" alt="image" src="https://user-images.githubusercontent.com/73976364/230632283-3626145a-04ed-4db1-9b6a-9c4cfe47d55c.png">

**Comment by z2332677** [comment]
这个 helper 的软件我在终端运行了

**Comment by z2332677** [comment]
![Uploading image.png…]()

**Comment by z2332677** [comment]
<img width="585" alt="image" src="https://user-images.githubusercontent.com/73976364/230632401-d7ea0f5e-3045-49d3-bc8a-d8d66e6f2c34.png">

**Comment by z2332677** [comment]
这算配置失败吗?

**Comment by MuiseDestiny** [comment]
密钥配置了吗，需要新建一个txt。

**Comment by z2332677** [comment]
配置了,

**Comment by z2332677** [comment]
这个密钥可以用,刚刚测试了

**Comment by MuiseDestiny** [comment]
那在zotero这边问他有回答吗，右下角有弹窗是怎么样的

**Comment by z2332677** [comment]
<img width="570" alt="image" src="https://user-images.githubusercontent.com/73976364/230637838-b518ce19-7981-4e10-9406-177cdb2a84f3.png">
在发生错误之后
<img width="982" alt="image" src="https://user-images.githubusercontent.com/73976364/230637950-81a25612-7904-4da7-9f3c-8cebde0e731b.png">

**Comment by MuiseDestiny** [comment]
它怎么还emo起来了哈哈哈

**Comment by z2332677** [comment]
![Uploading image.png…]()
他是真 emo.

**Comment by z2332677** [comment]
我这显示密钥有问题,可是这个密钥我用翻译插件是没问题的 还有输入密钥后这个文件夹里面是 51 字符吗?

**Comment by z2332677** [comment]
正常运行了

**Comment by MuiseDestiny** [comment]
> 正常运行了

有截图吗看看

**Comment by The-New-Coder** [comment]
pip **intstall** -r requirements.txt    大佬，给的教程里“intstall”拼错了😂   虽然但是  小白直接复制会不知道错误在哪（比如我）

**Comment by MuiseDestiny** [comment]
> pip **intstall** -r requirements.txt 大佬，给的教程里“intstall”拼错了😂 虽然但是 小白直接复制会不知道错误在哪（比如我）

抱歉

**Comment by The-New-Coder** [comment]
zotero-gpt-helper>python main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from langchain.chat_models import ChatOpenAI
ModuleNotFoundError: No module named 'langchain.chat_models'
求助🤣

**Comment by MuiseDestiny** [comment]
> zotero-gpt-helper>python main.py Traceback (most recent call last): File "main.py", line 4, in from langchain.chat_models import ChatOpenAI ModuleNotFoundError: No module named 'langchain.chat_models' 求助🤣

pip install langchain==0.0.130

**Comment by z2332677** [comment]
<img width="541" alt="image" src="https://user-images.githubusercontent.com/73976364/230706770-4a1786b5-20f4-45ca-836f-50e89a2ac9f4.png">

**Comment by z2332677** [comment]
正常使用 请问他回答速度的快慢和我使用的节点有关吗?

**Comment by MuiseDestiny** [comment]
> 正常使用 请问他回答速度的快慢和我使用的节点有关吗?

有关，一般第一个问题建立索引慢一点。后面的就快了。跟你号的权限也有关。

**Comment by z2332677** [comment]
有个小问题 就是更新之后,每问一次问题都要重新按一下 ask pdf 吗?

**Comment by MuiseDestiny** [comment]
> 个小问题 就是更新之后,每问一次问题都要重新按一下 ask pdf 吗?

Yes. 因为回车是没有PDF作为背景的普通对话。

**Comment by z2332677** [comment]
那么这样会消耗更多的 token 吗?

**Comment by z2332677** [comment]
它是每次都重新读取这篇文章 然后消耗文章字符数的 token 吗?

**Comment by MuiseDestiny** [comment]
不会，会对得到的向量储存，具体阅读py源码

**Comment by lzy19950613** [comment]
> 请问你打通AskPDF了吗，因为我不确定文档写的是否详细，用户参照能否配置成功

没有..作者可否写一个面向编程小白的通用基础教程，最近好多都插件都是基于python，chatpaper,中科院学术优化等等，网上有一些教程指导基于annaconda来实现，在b站上有一定的点击和传播量，非常喜欢和支持您的作品，如果能更普适化一些或许会更好。
本插件我刚刚也在之前的基础上试了一下，可能还是我哪里没有配置好。 
VSCODE输出如下：
(base) C:\Software\zotero-gpt-helper-master>python main.py                   
 * Serving Flask app 'main'
 * Debug mode: on
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug: * Restarting with watchdog (windowsapi)
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 223-782-061
INFO:werkzeug:127.0.0.1 - - [10/Apr/2023 23:18:42] "GET / HTTP/1.1" 404 -

但是我打开这个网址，却提示：
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
如果您有时间希望得到回复，不甚感激。

**Comment by MuiseDestiny** [comment]
> 

这个网址不需要打开，这样就是成功开启了，然后再插件就可以点击askPDF了。有空录一个视频讲一下吧，因为一直在开发，没来得及细说明。

**Comment by lzy19950613** [comment]
> > 
> 
> 这个网址不需要打开，这样就是成功开启了，然后再插件就可以点击askPDF了。有空录一个视频讲一下吧，因为一直在开发，没来得及细说明。

是的！刚刚给您回复完我也发现了竟然已经可以运行了，再次感谢您，我去小小赞赏一下。
（是否考虑建立粉丝群呢，有些问题或许粉丝之间即可解答，青柠的商业道路目前看来比较成功，真心希望您得到一些回报

**Comment by MuiseDestiny** [comment]
> > > 
> > 
> > 
> > 这个网址不需要打开，这样就是成功开启了，然后再插件就可以点击askPDF了。有空录一个视频讲一下吧，因为一直在开发，没来得及细说明。
> 
> 是的！刚刚给您回复完我也发现了竟然已经可以运行了，再次感谢您，我去小小赞赏一下。 （是否考虑建立粉丝群呢，有些问题或许粉丝之间即可解答，青柠的商业道路目前看来比较成功，真心希望您得到一些回报

确实是很多重复问题的
