### ISSUE TITLE
作者你好，我在配置时碰到了如下问题，请问应该如何解决？

### ISSUE THREAD

**Issue by MrLittleShark** [MuiseDestiny/zotero-gpt-helper#3]
Traceback (most recent call last):
  File "D:\15. Python\lib\curses\__init__.py", line 54, in <module>
    has_key
NameError: name 'has_key' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Chen Zongbao\zotero-gpt-helper\main.py", line 4, in <module>
    from langchain.chat_models import ChatOpenAI
  File "D:\15. Python\lib\site-packages\langchain\__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "D:\15. Python\lib\site-packages\langchain\agents\__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "D:\15. Python\lib\site-packages\langchain\agents\agent.py", line 17, in <module>
    from langchain.chains.base import Chain
  File "D:\15. Python\lib\site-packages\langchain\chains\__init__.py", line 2, in <module>
    from langchain.chains.api.base import APIChain
  File "D:\15. Python\lib\site-packages\langchain\chains\api\base.py", line 8, in <module>
    from langchain.chains.api.prompt import API_RESPONSE_PROMPT, API_URL_PROMPT
  File "D:\15. Python\lib\site-packages\langchain\chains\api\prompt.py", line 2, in <module>
    from langchain.prompts.prompt import PromptTemplate
  File "D:\15. Python\lib\site-packages\langchain\prompts\__init__.py", line 12, in <module>
    from langchain.prompts.few_shot import FewShotPromptTemplate
  File "D:\15. Python\lib\site-packages\langchain\prompts\few_shot.py", line 11, in <module>
    from langchain.prompts.example_selector.base import BaseExampleSelector
  File "D:\15. Python\lib\site-packages\langchain\prompts\example_selector\__init__.py", line 3, in <module>
    from langchain.prompts.example_selector.semantic_similarity import (
  File "D:\15. Python\lib\site-packages\langchain\prompts\example_selector\semantic_similarity.py", line 8, in <module>
    from langchain.embeddings.base import Embeddings
  File "D:\15. Python\lib\site-packages\langchain\embeddings\__init__.py", line 18, in <module>
    from langchain.embeddings.openai import OpenAIEmbeddings
  File "D:\15. Python\lib\site-packages\langchain\embeddings\openai.py", line 9, in <module>
    from tenacity import (
  File "D:\15. Python\lib\site-packages\tenacity\__init__.py", line 549, in <module>
    from tenacity.tornadoweb import TornadoRetrying
  File "D:\15. Python\lib\site-packages\tenacity\tornadoweb.py", line 23, in <module>
    from tornado import gen
  File "D:\15. Python\lib\site-packages\tornado\gen.py", line 81, in <module>
    from tornado.concurrent import (
  File "D:\15. Python\lib\site-packages\tornado\concurrent.py", line 34, in <module>
    from tornado.log import app_log
  File "D:\15. Python\lib\site-packages\tornado\log.py", line 43, in <module>
    import curses
  File "D:\15. Python\lib\curses\__init__.py", line 56, in <module>
    from .has_key import has_key
  File "D:\15. Python\lib\curses\has_key.py", line 11, in <module>
    curses.KEY_A1: 'ka1',
AttributeError: partially initialized module 'curses' has no attribute 'KEY_A1' (most likely due to a circular import)

**Comment by MuiseDestiny** [comment]
密钥是否配置。

**Comment by MrLittleShark** [comment]
> 密钥是否配置。

已经配置了，会不会与网络环境相关。zotero的本地密钥需要配置吗

**Comment by MuiseDestiny** [comment]
pip uninstall langchain
pip install langchain==0.0.130

**Comment by MrLittleShark** [comment]
> pip uninstall langchain pip install langchain==0.0.130

好像问题还是存在诶

**Comment by MrLittleShark** [comment]
我更新一下python试试，似乎是curses模块出了问题

**Comment by MrLittleShark** [comment]
更新完就成功了hhh

**Comment by MrLittleShark** [comment]
* Serving Flask app 'main'
 * Debug mode: on
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 528-626-477
INFO:werkzeug:127.0.0.1 - - [08/Apr/2023 13:01:51] "GET / HTTP/1.1" 404 -
![image](https://user-images.githubusercontent.com/112299157/230704124-c8f614f0-8958-4ad4-b037-989d02cb9251.png)

**Comment by MrLittleShark** [comment]
然后需要怎么操作呢，打开gpt插件后也没有askpdf选项诶

**Comment by MuiseDestiny** [comment]
> 然后需要怎么操作呢，打开gpt插件后也没有askpdf选项诶

自己创建一个https://github.com/MuiseDestiny/zotero-gpt/blob/bootstrap/labels/AskPDF.txt

**Comment by MuiseDestiny** [comment]
输入标签回车，再粘贴剩下的内容

**Comment by MrLittleShark** [comment]
可以用了！！！！！Thank you very much！

**Comment by MuiseDestiny** [comment]
> 可以用了！！！！！Thank you very much！

截个图看看效果啊，我想知道有没有人成功

**Comment by MrLittleShark** [comment]
![image](https://user-images.githubusercontent.com/112299157/230708020-2a39662a-4106-4eb6-ab55-e05882693fc8.png)
dan但是要global模式，不然会显示  远程主机强迫关闭了一个现有的连接。

**Comment by The-New-Coder** [comment]
成功实现，也是更新python到最新版本后成功😎

**Comment by lvshuaiyang** [comment]
我也成功了，但是有时候gpt回答的东西并不是我提问的pdf，不晓得是哪一步出了问题。

**Comment by MuiseDestiny** [comment]
> 我也成功了，但是有时候gpt回答的东西并不是我提问的pdf，不晓得是哪一步出了问题。

需要点askPDF不要直接回车
